# Generated by Django 4.0.3 on 2022-04-04 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_service', '0005_creditors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choose_company', to='bank_service.entity')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choose_worker', to='bank_service.individual')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chose_company', to='payroll_project.add_worker')),
            ],
        ),
    ]
