# Generated by Django 4.0.3 on 2022-03-26 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_type', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bank_acc', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bank_type.choose_bank')),
                ('user', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_service.account')),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='Full Username')),
                ('password', models.CharField(max_length=9, unique=True, verbose_name='Password Data')),
                ('id_number', models.CharField(max_length=14, unique=True, verbose_name='Password ID')),
                ('user_tel', models.CharField(max_length=13, unique=True, verbose_name='User Telephone')),
                ('email', models.CharField(max_length=35, verbose_name='User email')),
                ('bank_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bank_type.choose_bank')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('IO', 'IO'), ('OOO', 'OOO'), ('ZAO', 'ZAO')], max_length=3, verbose_name='Entity Type')),
                ('entity_name', models.CharField(max_length=20, unique=True, verbose_name='Entity Name')),
                ('pay_acc_number', models.CharField(max_length=15, unique=True, verbose_name='Account Number')),
                ('ind_code', models.CharField(max_length=15, unique=True, verbose_name='Identification Code')),
                ('address', models.CharField(max_length=30, unique=True, verbose_name='Address')),
                ('bank_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bank_type.choose_bank')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='bank_service.account')),
            ],
        ),
    ]
