# Generated by Django 4.0.3 on 2022-03-30 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account_getter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_getter', to='bank_service.account')),
                ('account_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_sender', to='bank_service.account')),
            ],
        ),
    ]
