# Generated by Django 4.0.3 on 2022-04-02 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_service', '0003_frozen_acc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accumulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accumulated_account', to='bank_service.account')),
            ],
        ),
    ]
